spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: C0dingS@int
    
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8082
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  
#task-service:
#  ribbon:
#    listOfServers: http://localhost:8083/,http://localhost:8085/
